<a href="https://colab.research.google.com/github/JairGF05/manejo_datos_nulos_pandas/blob/main/manejo_datos_nulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
diccionario = {
    'Col1': [1,2,3,np.nan],
    'Col2:': [4, np.nan, 6, 7],
    'Col3':['a', 'b', 'c', None]
}
diccionario

{'Col1': [1, 2, 3, nan],
 'Col2:': [4, nan, 6, 7],
 'Col3': ['a', 'b', 'c', None]}

In [5]:
#Creacion de dataframe con Pandas, al forma se ve m√°s estructurada de esta forma
dataframe_diccionario = pd.DataFrame(diccionario)
dataframe_diccionario

   Col1  Col2:  Col3
0   1.0    4.0     a
1   2.0    NaN     b
2   3.0    6.0     c
3   NaN    7.0  None

In [6]:
#Forma de verificar valores nulos
dataframe_diccionario.isnull()

    Col1  Col2:   Col3
0  False  False  False
1  False   True  False
2  False  False  False
3   True  False   True

In [7]:
#Verificaci√≥n de nulidad usando un m√©todo n√∫merico
dataframe_diccionario.isnull()*1

   Col1  Col2:  Col3
0     0      0     0
1     0      1     0
2     0      0     0
3     1      0     1

In [8]:
#Una vez identificados los valores nulos, estos pueden ser reemplazados
dataframe_diccionario.fillna('Missing')

      Col1    Col2:     Col3
0      1.0      4.0        a
1      2.0  Missing        b
2      3.0      6.0        c
3  Missing      7.0  Missing

In [9]:
#Reemplazar los valosres nulos por la media
dataframe_diccionario.fillna(dataframe_diccionario.mean())

<ipython-input-9-be444bc4540c>:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  dataframe_diccionario.fillna(dataframe_diccionario.mean())

   Col1     Col2:  Col3
0   1.0  4.000000     a
1   2.0  5.666667     b
2   3.0  6.000000     c
3   2.0  7.000000  None

In [10]:
#Reemplazar valores, asumiendo la interpolaci√≥n de una serie
dataframe_diccionario.interpolate()

   Col1  Col2:  Col3
0   1.0    4.0     a
1   2.0    5.0     b
2   3.0    6.0     c
3   3.0    7.0  None

In [12]:
dataframe_diccionario

   Col1  Col2:  Col3
0   1.0    4.0     a
1   2.0    NaN     b
2   3.0    6.0     c
3   NaN    7.0  None

In [11]:
#Borrar los valores nulos
dataframe_diccionario.dropna()

   Col1  Col2: Col3
0   1.0    4.0    a
2   3.0    6.0    c